import { $ } from './dom.js';
import { icon } from './icons.js';
import { initDesktopWidgets, applyAppearance } from './widgets.js';
export function mountShell() {
  $('#app').innerHTML =
    `<div class="wallpaper" aria-hidden="true"></div><a class="plant-home" href="#" aria-label="Yard home">🪴</a><main><h1 class="sr-only">Yard desktop</h1><div id="owner-banner" class="banner" hidden>Friends and transfers are active in another Yard tab. <button id="focus-owner">Open active tab</button></div><div id="layout-help" class="banner" hidden>Drag title bars or use arrow keys to rearrange apps. <button id="restore-layout">Tidy up</button><div id="hidden-panels"></div></div><div class="desktop bento" id="bento" aria-label="Your desktop widgets"><section class="tile panel files-card" data-panel="files"><div class="window-bar"><button class="drag-handle" aria-label="Move Files; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="folder"></i></span>Files<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Files"><i data-icon="minus"></i></button></div><div class="window-content"><div class="panel-heading"><h2>Files</h2><button id="folder-menu" class="button" title="Choose a folder"><i data-icon="folder"></i> Choose folder</button></div><div class="folder-bar"><span id="folder-name">A home for your files</span><button id="reconnect-folder" class="text-button">Reconnect</button></div><div class="search"><i data-icon="search"></i><input id="file-search" placeholder="Find a file…" aria-label="Search loaded filenames"></div><div class="crumb"><button id="folder-up" class="text-button" hidden>← Back</button><span id="folder-path">LOCAL & PRIVATE</span><button id="refresh-folder" class="text-button">Refresh</button></div><div id="file-list" class="file-list"></div><div class="panel-footer"><span>Only shared when you choose.</span><button id="new-note" class="text-button">＋ New note</button></div></div></section>
<section class="tile panel storage-card" data-panel="storage"><div class="window-bar"><button class="drag-handle" aria-label="Move Storage; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="hard-drive"></i></span>Storage<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Storage"><i data-icon="minus"></i></button></div><div class="window-content"><div class="card-heading"><span class="connection-label">Browser storage</span><button id="refresh-storage" class="icon-button" aria-label="Refresh storage"><i data-icon="refresh-cw"></i></button></div><div class="storage-overview"><div id="storage-ring" class="storage-ring" role="img" aria-label="Checking browser storage"><div><strong id="storage-free">--</strong><span>available</span></div></div><div class="storage-copy"><p><strong id="storage-used">--</strong> of <span id="storage-total">--</span> used</p><p class="muted">Local notes, identity & preferences.</p></div></div><div class="category-row"><span class="category-icon"><i data-icon="folder"></i></span><div><strong>Connected folder</strong><span id="storage-folder">No folder selected</span></div></div><p class="coming-soon">Browser quota is an estimate. It does not measure your drive or connected folder.</p></div></section>
<section class="tile panel clock-card" data-panel="clock"><div class="window-bar"><button class="drag-handle" aria-label="Move Local time; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="clock-3"></i></span>Local time<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Local time"><i data-icon="minus"></i></button></div><div class="clock-content"><div class="analog-clock" role="img" aria-label="Current time"><span class="clock-number n12">12</span><span class="clock-number n3">3</span><span class="clock-number n6">6</span><span class="clock-number n9">9</span><div class="hand hour-hand"></div><div class="hand minute-hand"></div><div class="hand second-hand"></div><span class="clock-pin"></span><span class="clock-brand">YARD</span></div><time id="date"></time><p>Your local time.</p></div></section>
<section class="tile panel notes-card notes" data-panel="notes"><div class="window-bar"><button class="drag-handle" aria-label="Move Notes; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="sticky-note"></i></span>Notes<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Notes"><i data-icon="minus"></i></button></div><div class="notes-content"><div class="panel-heading"><h2>Notes</h2><div class="segmented"><button id="personal-tab" class="active">Personal</button><button id="shared-tab">Together</button></div></div><div class="note-meta"><span id="note-title">A little note to yourself</span><span id="note-state" aria-live="polite">Saved locally</span></div><textarea id="note-editor" spellcheck="true" maxlength="200000" placeholder="Ideas, reminders, a tiny to-do list…" aria-label="Note editor"></textarea><div class="panel-footer"><span id="note-hint">Yours to keep. Private by default.</span><div><button id="save-file" class="text-button" hidden>Save file</button><button id="export-note" class="text-button">Export note ↗</button></div></div></div></section>
<section class="tile panel people-card" data-panel="friends"><div class="window-bar"><button class="drag-handle" aria-label="Move Friends; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="users"></i></span>Friends<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Friends"><i data-icon="minus"></i></button></div><div class="window-content"><button id="profile-button" class="my-profile" aria-label="Edit your profile"><span id="my-avatar" class="friend-avatar">Y</span><span class="my-profile-copy"><strong id="greeting">Your profile</strong><span>Your little corner.</span></span><i data-icon="pencil"></i></button><div class="friend-tools"><button id="invite-button" class="button primary"><i data-icon="users"></i> Invite a friend</button><button id="start-room" class="text-button">Start hangout</button></div><div class="panel-heading"><h2>Friends</h2><button id="join-button" class="text-button">Join with code</button></div><div id="friends-list" class="friends-list"></div><div id="room-info" class="room-info"></div><div id="chat-log" class="chat-log" role="log" aria-live="polite"></div><form id="chat-form" class="chat-compose"><input id="chat-input" maxlength="4000" placeholder="Say something kind…" aria-label="Chat message"><button class="primary" aria-label="Send message">↑</button></form><div class="panel-footer"><span id="room-label">Small circles, real connection.</span><button id="nudge" class="text-button">♧ Nudge</button></div></div></section>
<section class="tile panel focus-card" data-panel="focus"><div class="window-bar"><button class="drag-handle" aria-label="Move Focus; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="timer"></i></span>Focus<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Focus"><i data-icon="minus"></i></button></div><div class="focus-content"><div class="timer-modes" aria-label="Timer mode"><button data-minutes="25" class="active" aria-pressed="true">Focus</button><button data-minutes="5" aria-pressed="false">Short break</button><button data-minutes="15" aria-pressed="false">Long break</button></div><div class="timer-face"><span aria-hidden="true"><i data-icon="timer"></i></span><output id="timer-time" aria-live="off" aria-label="Time remaining">25:00</output><span id="timer-label">ONE THING AT A TIME</span></div><div class="timer-controls"><button id="timer-toggle" class="button primary">▶ Start</button><button id="timer-reset" class="icon-button" aria-label="Reset timer"><i data-icon="rotate-ccw"></i></button></div><p id="timer-message" role="status">Focus timer. A little breathing room.</p></div></section>
<section class="tile panel transfers-card" data-panel="transfers"><div class="window-bar"><button class="drag-handle" aria-label="Move Transfers; use arrow keys to reorder" title="Drag to move · Arrow keys to reorder"><span><i data-icon="share-2"></i></span>Transfers<span class="grip" aria-hidden="true"><i data-icon="grip-vertical"></i></span></button><button class="minimize" aria-label="Hide Transfers"><i data-icon="minus"></i></button></div><div class="window-content"><div class="panel-heading"><h2>Pass something along</h2><button id="send-files" class="outline">＋ Send files</button></div><div id="transfer-list" class="transfer-list"></div><div class="panel-footer"><span>Up to 10 GB per file · direct to your friend</span><span class="subtle">Both Yards stay open</span></div></div></section></div></main><footer class="desktop-footer"><span id="signal" class="status"><i></i>Starting</span><span>Yard 0.1.0 · Your little corner</span><time id="time"></time></footer><nav class="dock" aria-label="Desktop apps"><button data-jump="files" title="Open Files" aria-pressed="true"><span class="dock-icon"><i data-icon="folder"></i></span><span>Files</span></button><button data-jump="storage" title="Open Storage" aria-pressed="true"><span class="dock-icon"><i data-icon="hard-drive"></i></span><span>Storage</span></button><button data-jump="clock" title="Open Local time" aria-pressed="true"><span class="dock-icon"><i data-icon="clock-3"></i></span><span>Clock</span></button><button data-jump="notes" title="Open Notes" aria-pressed="true"><span class="dock-icon"><i data-icon="sticky-note"></i></span><span>Notes</span></button><button data-jump="friends" title="Open Friends" aria-pressed="true"><span class="dock-icon"><i data-icon="users"></i></span><span>Friends</span></button><button data-jump="focus" title="Open Focus" aria-pressed="true"><span class="dock-icon"><i data-icon="timer"></i></span><span>Focus</span></button><button data-jump="transfers" title="Open Transfers" aria-pressed="true"><span class="dock-icon"><i data-icon="share-2"></i></span><span>Transfers</span></button><span class="dock-divider"></span><button id="layout-button" title="Edit desktop layout" aria-label="Edit desktop layout"><span class="dock-icon"><i data-icon="layout-grid"></i></span><span id="layout-label">Layout</span></button><button id="settings-button" title="Open Settings" aria-haspopup="dialog"><span class="dock-icon"><i data-icon="settings-2"></i></span><span>Settings</span></button></nav>
<div id="desktop-announcement" class="sr-only" role="status"></div><div id="toast" role="status" hidden></div><dialog id="dialog"><div id="dialog-content"></div></dialog>`;
  document.querySelectorAll('[data-icon]').forEach((node) => {
    node.outerHTML = icon(node.dataset.icon);
  });
}
export function initShell(state) {
  applyAppearance(state.settings);
  function greeting() {
    $('#greeting').textContent = state.settings.name || 'Your profile';
    $('#my-avatar').textContent = (state.settings.name || 'Y')[0].toUpperCase();
  }
  function clock() {
    const now = new Date();
    $('#time').textContent = now.toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
    });
    $('#date').textContent = now.toLocaleDateString([], {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
    });
    document.querySelector('.hour-hand').style.transform =
      `rotate(${(now.getHours() % 12) * 30 + now.getMinutes() / 2}deg)`;
    document.querySelector('.minute-hand').style.transform =
      `rotate(${now.getMinutes() * 6 + now.getSeconds() / 10}deg)`;
    document.querySelector('.second-hand').style.transform =
      `rotate(${now.getSeconds() * 6}deg)`;
    document
      .querySelector('.analog-clock')
      .setAttribute('aria-label', `Local time: ${$('#time').textContent}`);
  }
  clock();
  setInterval(clock, 1000);
  greeting();
  initDesktopWidgets(state).catch(console.error);
  return { greeting };
}
